const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'shirts',
            images:'/image/p6.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Lacoste free Shirt',
            category:'shirts',
            images:'/image/p1.jpg',
            price:220,
            brand:'Lacoste',
            rating:4.8,
            numReviews:14,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Turtel Slim Shirt',
            category:'shirts',
            images:'/image/p3.jpg',
            price:500,
            brand:'Turtel',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Denim Slim Shirt',
            category:'shirts',
            images:'/image/p4.jpg',
            price:800,
            brand:'Denim',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'leecooper Slim Shirt',
            category:'shirts',
            images:'/image/p5.jpg',
            price:120,
            brand:'leecooper',
            rating:4.2,
            numReviews:18,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'flying Machine Shirt',
            category:'shirts',
            images:'/image/p2.jpg',
            price:499,
            brand:'flying',
            rating:4.5,
            numReviews:15,
            description:'high quality product',
        },
    ],
};

export default data;